let Data = [
  {
    id: "1",
    title: "Educated",
    category: "swipes",
    locked: "unlocked",
    image: "../static/achievementimages/educated.png",
    explanation: "You have had your 10th lesson",
    date: "20-4-2022",
  },
  {
    id: "2",
    title: "Gave a lesson",
    category: "swipes",
    locked: "unlocked",
    image: "../static/achievementimages/lesson.png",
    explanation: "You gave your first lesson",
    date: "20-4-2022",
  },
  {
    id: "3",
    title: "Profile completed",
    category: "swipes",
    locked: "unlocked",
    image: "../static/achievementimages/profile.png",
    explanation: "You completed your profile",
    date: "20-4-2022",
  },
  {
    id: "4",
    title: "Reach level 10",
    category: "matches",
    locked: "unlocked",
    image: "../static/achievementimages/level10.png",
    explanation: "You have reached level 10",
    date: "20-4-2022",
  },
  {
    id: "5",
    title: "Student",
    category: "matches",
    locked: "unlocked",
    image: "../static/achievementimages/reading.png",
    explanation: "You have had your 5th lesson",
    date: "20-4-2022",
  },
  {
    id: "6",
    title: "Wants to learn",
    category: "matches",
    locked: "unlocked",
    image: "../static/achievementimages/books.png",
    explanation: "You have had your first lesson",
    date: "20-4-2022",
  },
  {
    id: "7",
    title: "Rich I",
    category: "profile",
    locked: "locked",
    image: "../static/achievementimages/coins.png",
    explanation: "You earned 1000 Educoins",
    date: "20-4-2022",
  },
  {
    id: "8",
    title: "Profile completed",
    category: "profile",
    locked: "locked",
    image: "../static/achievementimages/profile.png",
    explanation: "Your profile is completed",
    date: "20-4-2022",
  },
  {
    id: "9",
    title: "Rich II",
    category: "profile",
    locked: "locked",
    image: "../static/achievementimages/coins.png",
    explanation: "You earned 2000 Educoins",
    date: "20-4-2022",
  },
  {
    id: "10",
    title: "Reach level 20",
    category: "profile",
    locked: "locked",
    image: "../static/achievementimages/level10.png",
    explanation: "You reached level 20",
    date: "20-4-2022",
  },
];

let AchievementsOnProfile = {
  img1: "../static/achievementimages/books.png",
  img2: "../static/achievementimages/educated.png",
  img3: "../static/achievementimages/lesson.png",
};
